### ISSUE TITLE
support business devices on port 1515 (net socket)

### ISSUE THREAD

**Issue by DanielRuf** [phillipsnick/samsung-tv#10]
The message starts with the header `0xAA` (which has to be skipped in the checksum calculation) and they use the MDC protocol over TCP port `1515`.

**Comment by andreapx** [comment]
+1

**Comment by andreapx** [comment]
Is this feature been developed or has it been closed because it will not be developed?

**Comment by DanielRuf** [comment]
See https://github.com/phillipsnick/samsung-tv/issues/7

**Comment by DanielRuf** [comment]
But I have no Samsung TV so I can not test or develop further.
Contributors and PRs are very welcome.

**Comment by andreapx** [comment]
I wish I could help but I don't understand much about code...
