### ISSUE TITLE
skip first byte for checksum calculation (newer models)

### ISSUE THREAD

**Issue by DanielRuf** [phillipsnick/samsung-tv#7]
For `AA 11 FF 01 01` the checksum is `12`.

```
All communications take place in hexadecimals. The checksum is calculated by adding up all
values except the header. If a checksum adds up to be more than 2 digits as shown below
(11+FF+01+01=112), the first digit is removed.
```

Maybe we can add an optional parameter `skipHeader` which skips the first byte in the checksum calculation method or add another optional parameter for adding the length and position of the header which should not be included in the checksum calculation.

**Comment by phillipsnick** [comment]
@DanielRuf are you interested in being a collaborator on this project? I haven't got time to maintain this at the moment!

**Comment by DanielRuf** [comment]
> @DanielRuf are you interested in being a collaborator on this project? I haven't got time to maintain this at the moment!

I am not sure if I have so much time too but I can contribute as much as possible.

**Comment by phillipsnick** [comment]
Have added you as a collaborator anyway, just realised I don't even own a Samsung TV anymore!

**Comment by DanielRuf** [comment]
@phillipsnick thought about different approaches, so other users can also use this library for Samsung (and possibly other devices).

Optional method parameters like
```
caclulcateChecksum - true by default (for example if the checksum is not provided)
skipHeader / skipPrefix - false by default (not sure if this is always just one byte, skip first byte for checksum caculation)
```
Any other useful optional parameters which do not break old implementations?
